### ISSUE TITLE
Errors while running "python3 mudpd.py

### ISSUE THREAD

**Issue by bsmojoman** [usnistgov/MUD-PD#14]
ait@ait-OptiPlex-3060:~/github_tools/MUD-PD$ python3 mudpd.py
Traceback (most recent call last):
  File "/home/ait/github_tools/MUD-PD/mudpd.py", line 4026, in <module>
    logger.info("\thashlib:\t%s", getversion.get_module_version(hashlib)[0])
  File "/home/ait/.local/lib/python3.10/site-packages/getversion/main.py", line 248, in get_module_version
    raise ModuleVersionNotFound(original_module, errors_dict=all_errors)
getversion.main.ModuleVersionNotFound: Unable to get version for module 'hashlib'. Results:
 - Attempts for module 'hashlib':
   - <get_module_version_attr>: module 'hashlib' has no attribute '__version__'
   - <get_version_using_pkgresources>: Invalid version number: None
   - <get_builtin_module_version>: No such version: 3.10
   - <get_unzipped_wheel_or_egg_version>: module 'hashlib' has no attribute '__path__'
   - <get_version_using_setuptools_scm>: Unable to find SCM information (/.git or /.hg folder, typically) in the parent folders of /usr/lib/python3.10/hashlib.py

**Comment by bsmojoman** [comment]
Install of muddy: 

ait@ait-OptiPlex-3060:~/github_tools/MUD-PD/muddy$ ls
Dockerfile  docs  __init__.py  LICENSE  muddy  __pycache__  README.md  requirements.txt  setup.py

**Comment by bsmojoman** [comment]
ait@ait-OptiPlex-3060:~/github_tools/MUD-PD$ pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python==8.0.*,>=8.0.26 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (8.0.33)
Requirement already satisfied: pyshark==0.4.*,>=0.4.3 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: requests==2.26.*,>=2.26.0 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.26.0)
Requirement already satisfied: overload==1.*,>=1.1 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.1)
Requirement already satisfied: IPy~=1.0 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.1)
Requirement already satisfied: getversion~=1.0.2 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (1.0.2)
Requirement already satisfied: Pillow~=8.3.2 in /home/ait/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (8.3.2)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in /usr/lib/python3/dist-packages (from mysql-connector-python==8.0.*,>=8.0.26->-r requirements.txt (line 1)) (3.12.4)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from pyshark==0.4.*,>=0.4.3->-r requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: py in /home/ait/.local/lib/python3.10/site-packages (from pyshark==0.4.*,>=0.4.3->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pyshark==0.4.*,>=0.4.3->-r requirements.txt (line 2)) (21.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.26.*,>=2.26.0->-r requirements.txt (line 3)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.26.*,>=2.26.0->-r requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ait/.local/lib/python3.10/site-packages (from requests==2.26.*,>=2.26.0->-r requirements.txt (line 3)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.26.*,>=2.26.0->-r requirements.txt (line 3)) (3.3)
Requirement already satisfied: stdlib-list in /home/ait/.local/lib/python3.10/site-packages (from getversion~=1.0.2->-r requirements.txt (line 6)) (0.8.0)
Requirement already satisfied: setuptools-scm in /home/ait/.local/lib/python3.10/site-packages (from getversion~=1.0.2->-r requirements.txt (line 6)) (7.1.0)
Requirement already satisfied: setuptools in /home/ait/.local/lib/python3.10/site-packages (from setuptools-scm->getversion~=1.0.2->-r requirements.txt (line 6)) (49.2.1)
Requirement already satisfied: typing-extensions in /home/ait/.local/lib/python3.10/site-packages (from setuptools-scm->getversion~=1.0.2->-r requirements.txt (line 6)) (4.5.0)
Requirement already satisfied: tomli>=1.0.0 in /home/ait/.local/lib/python3.10/site-packages (from setuptools-scm->getversion~=1.0.2->-r requirements.txt (line 6)) (2.0.1)

**Comment by bsmojoman** [comment]
Ok - in the mudpd.py file, I commented out these lines of code then am able to bring up the GUI.

    # Installed package info
    logger.info("Installed Python Packages:")
    logger.info("\tgetversion:\t%s", getversion.get_module_version(getversion)[0])
#    logger.info("\thashlib:\t%s", getversion.get_module_version(hashlib)[0])
    logger.info("\tIPy:\t%s", getversion.get_module_version(IPy)[0])
    logger.info("\tpyshark:\t%s", getversion.get_module_version(pyshark)[0])
    logger.info("\tjson:\t%s", getversion.get_module_version(json)[0])
    logger.info("\tlogging:\t%s", getversion.get_module_version(logging)[0])
#    logger.info("\tmultiprocessing:\t%s", getversion.get_module_version(mp)[0])
    logger.info("\tmysql.connector:\t%s", getversion.get_module_version(mysql.connector)[0])
#    logger.info("\tos:\t%s", getversion.get_module_version(os)[0])
#    logger.info("\tsocket:\t%s", getversion.get_module_version(socket)[0])
    logger.info("\tsys:\t%s", getversion.get_module_version(sys)[0])
    logger.info("\ttime:\t%s", getversion.get_module_version(time)[0])
#    logger.info("\ttkinter:\t%s", getversion.get_module_version(tk)[0])

**Comment by bsmojoman** [comment]
some of this seems like its written for legacy python3 where some of the packages are built in to the python distribution.
